### ISSUE TITLE
Cannot register on Bug tracker

### ISSUE THREAD

**Issue by fairking** [audacious-media-player/libaudclient#1]
Hi guys, I am writing here as the only way to contact you.

The [bug tracker](https://redmine.audacious-media-player.org/projects/audacious/issues) is not accessible. On email verification there is no email sent to the inbox.

So the issue I am having with Audacious is it throws an error when I try to open Nextcloud folder:
> Error reading davs://john@myserver.com/remote.php/webdav/Music: Unknown URI scheme

Please fix this bug otherwise the app is not useful :-(

Thanks

![image](https://user-images.githubusercontent.com/13495631/219868006-2ae5b024-7d18-42a8-ac95-cf101960b1ca.png)

**Comment by jlindgren90** [comment]
Thanks for letting us know about the bug tracker.
This is not a bug. We don't support Nextcloud.
